# Generated by Django 3.2.9 on 2021-12-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery_items', models.TextField(verbose_name=50)),
                ('electronic_items', models.TextField(verbose_name=50)),
                ('clothing_items', models.TextField(verbose_name=50)),
                ('add_items', models.TextField(verbose_name=50)),
            ],
        ),
    ]
